// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoWebCitas.Models;

#nullable disable

namespace ProyectoWebCitas.Migrations
{
    [DbContext(typeof(ProyectoCitasContext))]
    partial class ProyectoCitasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoWebCitas.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .HasColumnType("int")
                        .HasColumnName("id_genero");

                    b.Property<string>("Genero1")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("genero");

                    b.HasKey("IdGenero")
                        .HasName("PK__GENERO__99A8E4F9E7DE1364");

                    b.ToTable("GENERO", (string)null);
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPermiso")
                        .HasName("PK__PERMISO__228F224F4ADE04DF");

                    b.ToTable("PERMISO", (string)null);
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.PermisoRol", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado");

                    b.HasKey("IdPermiso", "IdRol")
                        .HasName("PK__PERMISO___3424E9117E565DCF");

                    b.HasIndex("IdRol");

                    b.ToTable("PERMISO_ROL", (string)null);
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.Usuario", b =>
                {
                    b.Property<long>("Nuip")
                        .HasColumnType("bigint")
                        .HasColumnName("nuip");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Nuip")
                        .HasName("PK_nuip");

                    b.HasIndex("IdRol");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.PermisoRol", b =>
                {
                    b.HasOne("ProyectoWebCitas.Models.Permiso", "Permiso")
                        .WithMany("PermisoRoles")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoWebCitas.Models.Rol", "Rol")
                        .WithMany("PermisoRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoWebCitas.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.Permiso", b =>
                {
                    b.Navigation("PermisoRoles");
                });

            modelBuilder.Entity("ProyectoWebCitas.Models.Rol", b =>
                {
                    b.Navigation("PermisoRoles");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
